import request from "@/utils/request";
import {filterList} from "@/views/project/components/utils";

export function addProject(projectInfoForm, projectMemberForm, projectFundsForm, zxFundsDetailForm, zcFundsDetailForm, fundsSourceForm, projectIndicatorForm, projectPlanForm, otherAttachmentForm) {
    const members = filterList(projectMemberForm.items).map(value => {
        return {userId: value.id, projectUserRole: value.role}
    });
    const indicators = filterList(projectIndicatorForm.items).map(value => {
        return {targetName: value.title, midtermTarget: value.midterm, endTarget: value.finish}
    });
    const plans = filterList(projectPlanForm.items, "date").map(value => {
        return {stageStartDate: value.date[0], stageEndDate: value.date[1], stageTask: value.task}
    })
    console.log(otherAttachmentForm.uploadList);
    return request({
        url: '/project/my/add', method: 'post', data: {
            "projectBaseInfoBO"  : {
                "leadingUnit"                   : projectInfoForm.leadingUnit,
                "assignedSubjectName"           : projectInfoForm.name,
                "projectContact"                : projectInfoForm.contact,
                "projectAssignmentSerialNo"     : projectInfoForm.projectNumber,
                "projectSource"                 : projectInfoForm.source,
                "projectLevel"                  : projectInfoForm.level,
                "hasLeadingRole"                : projectInfoForm.isLeadingUnit,
                "assignedSubjectSection"        : projectInfoForm.subjectName,
                "subjectAssignmentSerialNo"     : projectInfoForm.subjectNumber,
                "projectEstablishTime"          : projectInfoForm.startTime,
                "projectScheduledCompletionTime": projectInfoForm.endTime,
                "projectDuration"               : projectInfoForm.duration,
                "significanceAndNecessity"      : projectInfoForm.meaning,
                "projectProgressStatus"         : projectInfoForm.progressStatus,
                "completionProgress"            : projectInfoForm.completionProgress,
                "collaboratingUnit"             : projectInfoForm.coopUnit,
                "expertTeam"                    : projectInfoForm.expertTeam,
                "awardDetails"                  : projectInfoForm.awardStatus,
                "publicationDetails"            : projectInfoForm.paperStatus,
                "patentDetails"                 : projectInfoForm.patentStatus,
                "softwareCopyrightDetails"      : projectInfoForm.rzStatus,
                "standardDetails"               : projectInfoForm.standardStatus,
            },
            "projectFundsBO"     : {
                "totalFundsAll"  : projectFundsForm.jfze,
                "totalFundsZx"   : projectFundsForm.zxjfze,
                "sbfZx"          : projectFundsForm.zxsbf,
                "totalFundsZxZj" : projectFundsForm.zxzjx,
                "totalFundsZxJj" : projectFundsForm.zxjjy,
                "totalFundsZc"   : projectFundsForm.zcjfze,
                "sbfZc"          : projectFundsForm.zcsbf,
                "totalFundsZcZj" : projectFundsForm.zczjx,
                "totalFundsZcJj" : projectFundsForm.zcjjy,
                "sbfZxZj"        : zxFundsDetailForm.sbf_zj,
                "sbfZcZj"        : zcFundsDetailForm.sbf_zj,
                "sbfGzsbZxZj"    : zxFundsDetailForm.gzsbf_zj,
                "sbfGzsbZcZj"    : zcFundsDetailForm.gzsbf_zj,
                "sbfSzsbZxZj"    : zxFundsDetailForm.szsbf_zj,
                "sbfSzsbZcZj"    : zcFundsDetailForm.szsbf_zj,
                "sbfSbgzyzlZxZj" : zxFundsDetailForm.sbgzyzlf_zj,
                "sbfSbgzyzlZcZj" : zcFundsDetailForm.sbgzyzlf_zj,
                "clfZxZj"        : zxFundsDetailForm.clf_zj,
                "clfZcZj"        : zcFundsDetailForm.clf_zj,
                "kyhdfZxZj"      : zxFundsDetailForm.kyhdf_zj,
                "kyhdfZcZj"      : zcFundsDetailForm.kyhdf_zj,
                "kyhdfZlZxZj"    : zxFundsDetailForm.zlf_zj,
                "kyhdfZlZcZj"    : zcFundsDetailForm.zlf_zj,
                "kyhdfCshyjgZxZj": zxFundsDetailForm.cshyjgf_zj,
                "kyhdfCshyjgZcZj": zcFundsDetailForm.cshyjgf_zj,
                "kyhdfBgZxZj"    : zxFundsDetailForm.bgf_zj,
                "kyhdfBgZcZj"    : zcFundsDetailForm.bgf_zj,
                "kyhdfSjybcjZxZj": zxFundsDetailForm.sjybcjf_zj,
                "kyhdfSjybcjZcZj": zcFundsDetailForm.sjybcjf_zj,
                "kyhdfYscbZxZj"  : zxFundsDetailForm.yscbf_zj,
                "kyhdfYscbZcZj"  : zcFundsDetailForm.yscbf_zj,
                "kyhdfZscqswZxZj": zxFundsDetailForm.zscqswf_zj,
                "kyhdfZscqswZcZj": zcFundsDetailForm.zscqswf_zj,
                "kyhdfRldlZxZj"  : zxFundsDetailForm.rldlf_zj,
                "kyhdfRldlZcZj"  : zcFundsDetailForm.rldlf_zj,
                "kyhdfClsyZxZj"  : zxFundsDetailForm.clsyf_zj,
                "kyhdfClsyZcZj"  : zcFundsDetailForm.clsyf_zj,
                "kyfwfZxZj"      : zxFundsDetailForm.kyfwf_zj,
                "kyfwfZcZj"      : zcFundsDetailForm.kyfwf_zj,
                "kyfwfZjzxZxZj"  : zxFundsDetailForm.zjzxf_zj,
                "kyfwfZjzxZcZj"  : zcFundsDetailForm.zjzxf_zj,
                "kyfwfClZxZj"    : zxFundsDetailForm.chlf_zj,
                "kyfwfClZcZj"    : zcFundsDetailForm.chlf_zj,
                "kyfwfHyhwZxZj"  : zxFundsDetailForm.hyhwf_zj,
                "kyfwfHyhwZcZj"  : zcFundsDetailForm.hyhwf_zj,
                "kyfwfGjhzjlZxZj": zxFundsDetailForm.gjhzjlf_zj,
                "kyfwfGjhzjlZcZj": zcFundsDetailForm.gjhzjlf_zj,
                "kyfwfGnxzZxZj"  : zxFundsDetailForm.gnxzf_zj,
                "kyfwfGnxzZcZj"  : zxFundsDetailForm.gnxzf_zj,
                "ryhlwbzfZxZj"   : zxFundsDetailForm.rylwbzf_zj,
                "ryhlwbzfZcZj"   : zcFundsDetailForm.rylwbzf_zj,
                "jxzcZx"         : zxFundsDetailForm.jxzc_jj,
                "jxzcZc"         : zcFundsDetailForm.jxzc_jj,
                "othersZx"       : 0,
                "othersZc"       : 0,
                "jflyZx"         : fundsSourceForm.zxjfzz,
                "jflyZc"         : fundsSourceForm.zcjf,
                "jflyQtczbkZc"   : fundsSourceForm.qtczbk,
                "jflyDwzyhbzjZc" : fundsSourceForm.zyhbzj,
                "jflyQtzjZc"     : fundsSourceForm.qtzj,
                "sbfZxJj"        : zxFundsDetailForm.sbf_jj,
                "sbfZcJj"        : zcFundsDetailForm.sbf_jj,
                "sbfGzsbZxJj"    : zxFundsDetailForm.gzsbf_jj,
                "sbfGzsbZcJj"    : zcFundsDetailForm.gzsbf_jj,
                "sbfSzsbZxJj"    : zxFundsDetailForm.szsbf_jj,
                "sbfSzsbZcJj"    : zcFundsDetailForm.szsbf_jj,
                "sbfSbgzyzlZxJj" : zxFundsDetailForm.sbgzyzlf_jj,
                "sbfSbgzyzlZcJj" : zcFundsDetailForm.sbgzyzlf_jj,
                "clfZxJj"        : zxFundsDetailForm.clf_jj,
                "clfZcJj"        : zcFundsDetailForm.clf_jj,
                "kyhdfZxJj"      : zxFundsDetailForm.kyhdf_jj,
                "kyhdfZcJj"      : zcFundsDetailForm.kyhdf_jj,
                "kyhdfZlZxJj"    : zxFundsDetailForm.zlf_jj,
                "kyhdfZlZcJj"    : zcFundsDetailForm.zlf_jj,
                "kyhdfCshyjgZxJj": zxFundsDetailForm.cshyjgf_jj,
                "kyhdfCshyjgZcJj": zcFundsDetailForm.cshyjgf_jj,
                "kyhdfBgZxJj"    : zxFundsDetailForm.bgf_jj,
                "kyhdfBgZcJj"    : zcFundsDetailForm.bgf_jj,
                "kyhdfSjybcjZxJj": zxFundsDetailForm.sjybcjf_jj,
                "kyhdfSjybcjZcJj": zcFundsDetailForm.sjybcjf_jj,
                "kyhdfYscbZxJj"  : zxFundsDetailForm.yscbf_jj,
                "kyhdfYscbZcJj"  : zcFundsDetailForm.yscbf_jj,
                "kyhdfZscqswZxJj": zxFundsDetailForm.zscqswf_jj,
                "kyhdfZscqswZcJj": zcFundsDetailForm.zscqswf_jj,
                "kyhdfRldlZxJj"  : zxFundsDetailForm.rldlf_jj,
                "kyhdfRldlZcJj"  : zcFundsDetailForm.rldlf_jj,
                "kyhdfClsyZxJj"  : zxFundsDetailForm.clsyf_jj,
                "kyhdfClsyZcJj"  : zcFundsDetailForm.clsyf_jj,
                "kyfwfZxJj"      : zxFundsDetailForm.kyfwf_jj,
                "kyfwfZcJj"      : zcFundsDetailForm.kyfwf_jj,
                "kyfwfZjzxZxJj"  : zxFundsDetailForm.zjzxf_jj,
                "kyfwfZjzxZcJj"  : zcFundsDetailForm.zjzxf_jj,
                "kyfwfClZxJj"    : zxFundsDetailForm.chlf_jj,
                "kyfwfClZcJj"    : zcFundsDetailForm.chlf_jj,
                "kyfwfHyhwZxJj"  : zxFundsDetailForm.hyhwf_jj,
                "kyfwfHyhwZcJj"  : zcFundsDetailForm.hyhwf_jj,
                "kyfwfGjhzjlZxJj": zxFundsDetailForm.gjhzjlf_jj,
                "kyfwfGjhzjlZcJj": zcFundsDetailForm.gjhzjlf_jj,
                "kyfwfGnxzZxJj"  : zxFundsDetailForm.gnxzf_jj,
                "kyfwfGnxzZcJj"  : zxFundsDetailForm.gnxzf_jj,
                "ryhlwbzfZxJj"   : zxFundsDetailForm.rylwbzf_jj,
                "ryhlwbzfZcJj"   : zcFundsDetailForm.rylwbzf_jj,
            },
            "projectUserBoList"  : members,
            "projectTargetBOList": indicators,
            "projectPlanBOList"  : plans,
            "ossIdList"          : otherAttachmentForm.uploadList,
        }
    })
}
