import request from "@/utils/request";
import {filterList} from "@/views/project/components/utils";

export function addProject(projectInfoForm, projectMemberForm,
                           projectFundsForm, zxFundsDetailForm,
                           zcFundsDetailForm, fundsSourceForm,
                           projectIndicatorForm, projectPlanForm,
                           otherAttachmentForm) {
    const members = filterList(projectMemberForm.items).map(value => {
        return {userId: value.id, projectUserRole: value.role}
    });
    const indicators = filterList(projectIndicatorForm.items).map(value => {
        return {targetName: value.title, midtermTarget: value.midterm, endTarget: value.finish}
    });
    const plans = filterList(projectPlanForm.items, "date").map(value => {
        return {stageStartDate: value.date[0], stageEndDate: value.date[1], stageTask: value.task}
    })
    console.log(otherAttachmentForm.uploadList);
    return request({
        url: '/project/my/add',
        method: 'post',
        data: {
            "projectBaseInfoBO": {
                "leadingUnit": projectInfoForm.leadingUnit,
                "assignedSubjectName": projectInfoForm.name,
                "projectContact": projectInfoForm.contact,
                "projectAssignmentSerialNo": projectInfoForm.projectNumber,
                "projectSource": projectInfoForm.source,
                "projectLevel": projectInfoForm.level,
                "hasLeadingRole": projectInfoForm.isLeadingUnit,
                "assignedSubjectSection": projectInfoForm.subjectName,
                "subjectAssignmentSerialNo": projectInfoForm.subjectNumber,
                "projectEstablishTime": projectInfoForm.startTime,
                "projectScheduledCompletionTime": projectInfoForm.endTime,
                "projectDuration": projectInfoForm.duration,
                "significanceAndNecessity": projectInfoForm.meaning,
                "projectProgressStatus": projectInfoForm.progressStatus,
                "completionProgress": projectInfoForm.completionProgress,
                "collaboratingUnit": projectInfoForm.coopUnit,
                "expertTeam": projectInfoForm.expertTeam,
                "awardDetails": projectInfoForm.awardStatus,
                "publicationDetails": projectInfoForm.paperStatus,
                "patentDetails": projectInfoForm.patentStatus,
                "softwareCopyrightDetails": projectInfoForm.rzStatus,
                "standardDetails": projectInfoForm.standardStatus,
            },
            "projectFundsBO": {
                "totalFundsAll": 11111,
                "totalFundsZx": 99,
                "sbfZx": 0,
                "totalFundsZxZj": 0,
                "totalFundsZxJj": 0,
                "totalFundsZc": 0,
                "sbfZc": 0,
                "totalFundsZcZj": 0,
                "totalFundsZcJj": 0,
                "sbfZxZj": 0,
                "sbfZcZj": 0,
                "sbfGzsbZxZj": 0,
                "sbfGzsbZcZj": 0,
                "sbfSzsbZxZj": 0,
                "sbfSzsbZcZj": 0,
                "sbfSbgzyzlZxZj": 0,
                "sbfSbgzyzlZcZj": 0,
                "clfZxZj": 0,
                "clfZcZj": 0,
                "kyhdfZxZj": 0,
                "kyhdfZcZj": 0,
                "kyhdfZlZxZj": 0,
                "kyhdfZlZcZj": 0,
                "kyhdfCshyjgZxZj": 0,
                "kyhdfCshyjgZcZj": 0,
                "kyhdfBgZxZj": 0,
                "kyhdfBgZcZj": 0,
                "kyhdfSjybcjZxZj": 0,
                "kyhdfSjybcjZcZj": 0,
                "kyhdfYscbZxZj": 0,
                "kyhdfYscbZcZj": 0,
                "kyhdfZscqswZxZj": 0,
                "kyhdfZscqswZcZj": 0,
                "kyhdfRldlZxZj": 0,
                "kyhdfRldlZcZj": 0,
                "kyhdfClsyZxZj": 0,
                "kyhdfClsyZcZj": 0,
                "kyfwfZxZj": 0,
                "kyfwfZcZj": 0,
                "kyfwfZjzxZxZj": 0,
                "kyfwfZjzxZcZj": 0,
                "kyfwfClZxZj": 0,
                "kyfwfClZcZj": 0,
                "kyfwfHyhwZxZj": 0,
                "kyfwfHyhwZcZj": 0,
                "kyfwfGjhzjlZxZj": 0,
                "kyfwfGjhzjlZcZj": 0,
                "kyfwfGnxzZxZj": 0,
                "kyfwfGnxzZcZj": 0,
                "ryhlwbzfZxZj": 0,
                "ryhlwbzfZcZj": 0,
                "jxzcZx": 0,
                "jxzcZc": 0,
                "othersZx": 0,
                "othersZc": 0,
                "jflyZx": 0,
                "jflyZc": 0,
                "jflyQtczbkZc": 0,
                "jflyDwzyhbzjZc": 0,
                "jflyQtzjZc": 0,
                "sbfZxJj": 0,
                "sbfZcJj": 0,
                "sbfGzsbZxJj": 0,
                "sbfGzsbZcJj": 0,
                "sbfSzsbZxJj": 0,
                "sbfSzsbZcJj": 0,
                "sbfSbgzyzlZxJj": 0,
                "sbfSbgzyzlZcJj": 0,
                "clfZxJj": 0,
                "clfZcJj": 0,
                "kyhdfZxJj": 0,
                "kyhdfZcJj": 0,
                "kyhdfZlZxJj": 0,
                "kyhdfZlZcJj": 0,
                "kyhdfCshyjgZxJj": 0,
                "kyhdfCshyjgZcJj": 0,
                "kyhdfBgZxJj": 0,
                "kyhdfBgZcJj": 0,
                "kyhdfSjybcjZxJj": 0,
                "kyhdfSjybcjZcJj": 0,
                "kyhdfYscbZxJj": 0,
                "kyhdfYscbZcJj": 0,
                "kyhdfZscqswZxJj": 0,
                "kyhdfZscqswZcJj": 0,
                "kyhdfRldlZxJj": 0,
                "kyhdfRldlZcJj": 0,
                "kyhdfClsyZxJj": 0,
                "kyhdfClsyZcJj": 0,
                "kyfwfZxJj": 0,
                "kyfwfZcJj": 0,
                "kyfwfZjzxZxJj": 0,
                "kyfwfZjzxZcJj": 0,
                "kyfwfClZxJj": 0,
                "kyfwfClZcJj": 0,
                "kyfwfHyhwZxJj": 0,
                "kyfwfHyhwZcJj": 0,
                "kyfwfGjhzjlZxJj": 0,
                "kyfwfGjhzjlZcJj": 0,
                "kyfwfGnxzZxJj": 0,
                "kyfwfGnxzZcJj": 0,
                "ryhlwbzfZxJj": 0,
                "ryhlwbzfZcJj": 0,
                "a":1211
            },
            "projectUserBoList": members,
            "projectTargetBOList": indicators,
            "projectPlanBOList": plans,
            "ossIdList": otherAttachmentForm.uploadList,


        }
    })
}
